import { pool } from "@/lib/db";

export type PosShopSettings = {
  defaultPaymentMethod: "cash" | "promptpay";
  promptpayId: string | null;
  receiptHeader: string | null;
  allowNegativeStock: boolean;
  publicMenuToken: string | null;
  onlineOrderingEnabled: boolean;
  /** เปิดจอครัว — ปิดบิล walk-in แล้วสร้างตั๋วครัวอัตโนมัติ */
  kitchenEnabled: boolean;
  /** NULL = ยังไม่เปิดร้านจริง (ยังล้างข้อมูลเทสได้) */
  liveAt: string | null;
  /** เดลิเวอรี่ */
  deliveryEnabled: boolean;
  deliveryFee: string;
  deliveryMinOrder: string;
  deliveryAreaNote: string | null;
};

type SettingsRow = {
  default_payment_method: "cash" | "promptpay";
  promptpay_id: string | null;
  receipt_header: string | null;
  allow_negative_stock: boolean;
  public_menu_token: string | null;
  online_ordering_enabled: boolean;
  kitchen_enabled: boolean;
  live_at: Date | string | null;
  delivery_enabled: boolean;
  delivery_fee: string;
  delivery_min_order: string;
  delivery_area_note: string | null;
};

const SETTINGS_RETURN = `default_payment_method, promptpay_id, receipt_header,
  allow_negative_stock, public_menu_token, online_ordering_enabled, kitchen_enabled, live_at,
  delivery_enabled, delivery_fee::text AS delivery_fee,
  delivery_min_order::text AS delivery_min_order, delivery_area_note`;

function mapSettings(r: SettingsRow): PosShopSettings {
  return {
    defaultPaymentMethod: r.default_payment_method,
    promptpayId: r.promptpay_id,
    receiptHeader: r.receipt_header,
    allowNegativeStock: r.allow_negative_stock,
    publicMenuToken: r.public_menu_token,
    onlineOrderingEnabled: r.online_ordering_enabled,
    kitchenEnabled: r.kitchen_enabled,
    liveAt:
      r.live_at == null
        ? null
        : r.live_at instanceof Date
          ? r.live_at.toISOString()
          : String(r.live_at),
    deliveryEnabled: r.delivery_enabled,
    deliveryFee: r.delivery_fee ?? "0.00",
    deliveryMinOrder: r.delivery_min_order ?? "0.00",
    deliveryAreaNote: r.delivery_area_note,
  };
}

/** Ensures a settings row exists (token generated by column default). */
export async function getPosShopSettings(userId: string): Promise<PosShopSettings> {
  const { rows } = await pool.query<SettingsRow>(
    `INSERT INTO pos_shop_settings (user_id)
     VALUES ($1)
     ON CONFLICT (user_id) DO UPDATE SET updated_at = pos_shop_settings.updated_at
     RETURNING ${SETTINGS_RETURN}`,
    [userId],
  );
  return mapSettings(rows[0]);
}

export type UpdatePosShopSettingsInput = {
  promptpayId?: string | null;
  receiptHeader?: string | null;
  defaultPaymentMethod?: "cash" | "promptpay";
  onlineOrderingEnabled?: boolean;
  kitchenEnabled?: boolean;
  /** ทางเดียว: ตั้ง live_at ได้ครั้งแรกครั้งเดียว ปลดล็อกไม่ได้ผ่าน API */
  goLive?: boolean;
  deliveryEnabled?: boolean;
  deliveryFee?: number;
  deliveryMinOrder?: number;
  deliveryAreaNote?: string | null;
};

export async function upsertPosShopSettings(
  userId: string,
  input: UpdatePosShopSettingsInput,
): Promise<PosShopSettings> {
  const { rows } = await pool.query<SettingsRow>(
    `INSERT INTO pos_shop_settings
       (user_id, promptpay_id, receipt_header, default_payment_method,
        online_ordering_enabled, kitchen_enabled, live_at,
        delivery_enabled, delivery_fee, delivery_min_order, delivery_area_note)
     VALUES (
       $1,
       $2,
       $3,
       COALESCE($4, 'cash'),
       COALESCE($7, false),
       COALESCE($8, false),
       CASE WHEN $9 THEN now() ELSE NULL END,
       COALESCE($10, false),
       COALESCE($11::numeric, 0),
       COALESCE($12::numeric, 0),
       $13
     )
     ON CONFLICT (user_id) DO UPDATE SET
       promptpay_id            = CASE WHEN $5 THEN $2 ELSE pos_shop_settings.promptpay_id END,
       receipt_header          = CASE WHEN $6 THEN $3 ELSE pos_shop_settings.receipt_header END,
       default_payment_method  = COALESCE($4, pos_shop_settings.default_payment_method),
       online_ordering_enabled = COALESCE($7, pos_shop_settings.online_ordering_enabled),
       kitchen_enabled         = COALESCE($8, pos_shop_settings.kitchen_enabled),
       -- one-way: เซ็ตได้เฉพาะตอนยัง NULL เท่านั้น
       live_at                 = COALESCE(pos_shop_settings.live_at,
                                          CASE WHEN $9 THEN now() ELSE NULL END),
       delivery_enabled        = COALESCE($10, pos_shop_settings.delivery_enabled),
       delivery_fee            = COALESCE($11::numeric, pos_shop_settings.delivery_fee),
       delivery_min_order      = COALESCE($12::numeric, pos_shop_settings.delivery_min_order),
       delivery_area_note      = CASE WHEN $14 THEN $13 ELSE pos_shop_settings.delivery_area_note END,
       updated_at              = now()
     RETURNING ${SETTINGS_RETURN}`,
    [
      userId,
      input.promptpayId ?? null,
      input.receiptHeader ?? null,
      input.defaultPaymentMethod ?? null,
      input.promptpayId !== undefined,
      input.receiptHeader !== undefined,
      input.onlineOrderingEnabled ?? null,
      input.kitchenEnabled ?? null,
      input.goLive === true,
      input.deliveryEnabled ?? null,
      input.deliveryFee != null ? input.deliveryFee.toFixed(2) : null,
      input.deliveryMinOrder != null ? input.deliveryMinOrder.toFixed(2) : null,
      input.deliveryAreaNote ?? null,
      input.deliveryAreaNote !== undefined,
    ],
  );
  if (!rows[0]) throw new Error("Could not upsert POS shop settings");
  return mapSettings(rows[0]);
}
