import { pool } from "@/lib/db";

export type PosShopSettings = {
  defaultPaymentMethod: "cash" | "promptpay";
  promptpayId: string | null;
  receiptHeader: string | null;
  allowNegativeStock: boolean;
  publicMenuToken: string | null;
  onlineOrderingEnabled: boolean;
  /** เปิดจอครัว — ปิดบิล walk-in แล้วสร้างตั๋วครัวอัตโนมัติ */
  kitchenEnabled: boolean;
};

type SettingsRow = {
  default_payment_method: "cash" | "promptpay";
  promptpay_id: string | null;
  receipt_header: string | null;
  allow_negative_stock: boolean;
  public_menu_token: string | null;
  online_ordering_enabled: boolean;
  kitchen_enabled: boolean;
};

const SETTINGS_RETURN = `default_payment_method, promptpay_id, receipt_header,
  allow_negative_stock, public_menu_token, online_ordering_enabled, kitchen_enabled`;

function mapSettings(r: SettingsRow): PosShopSettings {
  return {
    defaultPaymentMethod: r.default_payment_method,
    promptpayId: r.promptpay_id,
    receiptHeader: r.receipt_header,
    allowNegativeStock: r.allow_negative_stock,
    publicMenuToken: r.public_menu_token,
    onlineOrderingEnabled: r.online_ordering_enabled,
    kitchenEnabled: r.kitchen_enabled,
  };
}

/** Ensures a settings row exists (token generated by column default). */
export async function getPosShopSettings(userId: string): Promise<PosShopSettings> {
  const { rows } = await pool.query<SettingsRow>(
    `INSERT INTO pos_shop_settings (user_id)
     VALUES ($1)
     ON CONFLICT (user_id) DO UPDATE SET updated_at = pos_shop_settings.updated_at
     RETURNING ${SETTINGS_RETURN}`,
    [userId],
  );
  return mapSettings(rows[0]);
}

export type UpdatePosShopSettingsInput = {
  promptpayId?: string | null;
  receiptHeader?: string | null;
  defaultPaymentMethod?: "cash" | "promptpay";
  onlineOrderingEnabled?: boolean;
  kitchenEnabled?: boolean;
};

export async function upsertPosShopSettings(
  userId: string,
  input: UpdatePosShopSettingsInput,
): Promise<PosShopSettings> {
  const { rows } = await pool.query<SettingsRow>(
    `INSERT INTO pos_shop_settings
       (user_id, promptpay_id, receipt_header, default_payment_method,
        online_ordering_enabled, kitchen_enabled)
     VALUES (
       $1,
       $2,
       $3,
       COALESCE($4, 'cash'),
       COALESCE($7, false),
       COALESCE($8, false)
     )
     ON CONFLICT (user_id) DO UPDATE SET
       promptpay_id            = CASE WHEN $5 THEN $2 ELSE pos_shop_settings.promptpay_id END,
       receipt_header          = CASE WHEN $6 THEN $3 ELSE pos_shop_settings.receipt_header END,
       default_payment_method  = COALESCE($4, pos_shop_settings.default_payment_method),
       online_ordering_enabled = COALESCE($7, pos_shop_settings.online_ordering_enabled),
       kitchen_enabled         = COALESCE($8, pos_shop_settings.kitchen_enabled),
       updated_at              = now()
     RETURNING ${SETTINGS_RETURN}`,
    [
      userId,
      input.promptpayId ?? null,
      input.receiptHeader ?? null,
      input.defaultPaymentMethod ?? null,
      input.promptpayId !== undefined,
      input.receiptHeader !== undefined,
      input.onlineOrderingEnabled ?? null,
      input.kitchenEnabled ?? null,
    ],
  );
  if (!rows[0]) throw new Error("Could not upsert POS shop settings");
  return mapSettings(rows[0]);
}
